version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  labels:
  - dependencies
